Repository emeks-studio/sensum-mobile, pull requests merged in 2021-02, with the labels that each got.

#14 Refactor remove native base
  src/api/SensumApi.js
  src/assets/fonts/TitilliumWeb-Bold.ttf
  src/assets/fonts/TitilliumWeb-ExtraLight.ttf
  src/assets/fonts/TitilliumWeb-Light.ttf
  src/assets/fonts/TitilliumWeb-Regular.ttf
  src/assets/fonts/TitilliumWeb-SemiBold.ttf
  src/assets/img/sensum_logo.svg
  src/assets/img/theme-colors-extra.png
  src/assets/img/theme-colors-original.png
  src/assets/styles/ThemeSheet.js
  src/assets/styles/Themes.js
  src/assets/svgs/Logo.js
  src/assets/svgs/atom.svg
  src/assets/svgs/close.svg
  src/assets/svgs/controlBack.svg
  src/assets/svgs/controlForward.svg
  src/assets/svgs/controlMinus.svg
  src/assets/svgs/controlPlus.svg
  src/assets/svgs/eye.svg
  src/assets/svgs/pulse.svg
  src/assets/svgs/rings.svg
  src/components/AnimatedSensation.js
  src/components/App.js
  src/components/HomeScreen.js
  src/components/NewSensationForm.js
  src/components/NewSensationScreen.js
  src/components/SensationControls.js
  src/components/SensationItem.js
  src/components/SensationMessage.js
  src/components/SensationsScreen.js
  src/components/Tamagochi.js
  src/components/ui/AnimatedFadingIcon.js
  src/components/ui/SensumToast.js
  src/components/ui/Toast.js
  src/components/ui/TopBarTitle.js
  src/components/ui/index.js
  src/components/ui/useToast.js
  src/model/CarrierCrow.js
  src/model/Sensations.js
  src/util/theming.js
Labels: tech debt

#17 Fix splash screen showing behind app
  package-lock.json
  package.json
  src/components/App.js
Labels: bug

#18 [chore] Update readme with sensum bot
  README.md
Labels: documentation
